In [81]:
#Librerias a utilizar

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler

In [95]:
#Cargar el dataset
dataframe = pd.read_csv("usuarios_win_mac_lin.csv")

Preprocesamiento

In [108]:
#Creación del dataset de validación y de entrenamiento

X = np.array(dataframe.drop(['clase'],axis = 1))
y = np.array(dataframe['clase'])

validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)

Entrenamiento

In [109]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [110]:
#Observar las predicciones
predictions = model.predict(X_validation)
print(accuracy_score(Y_validation, predictions))

0.8235294117647058


Matriz de confusión y reporte de clasificación

In [113]:
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

[[16  0  2]
 [ 4  2  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       0.80      0.89      0.84        18
           1       1.00      0.33      0.50         6
           2       0.83      1.00      0.91        10

    accuracy                           0.82        34
   macro avg       0.88      0.74      0.75        34
weighted avg       0.85      0.82      0.80        34

